using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoProps
{
    internal class Car
    {
        /* When defining automatic properties, you simply specify the access modifier, underlying data 
        type, property name, and empty get/set scopes. At compile time, your type will be provided with an 
        autogenerated private backing field and a fitting implementation of the get/set logic*/
        public string PetName { get; set; }
        public int Speed { get; set; }
        public string Color { get; set; } 
        //public string MyWriteOnlyProp { set; } // This will cause compilation error
        public string MyReadOnlyProp { get; } // This is fine but above will generate compilation error

        public void DispalyStats() => Console.WriteLine("Name: {0} \nSpeed: {1} \nColor{2}", PetName, Speed, Color);
    }
}
